### PR TITLE
Make the M4 example work with Rust stable toolchain

### LINKED ISSUE #45: Blackpill example blink rate is wrong
It seems the blackpill example blinks at the incorrect rate. It should blink with one toggle per second (0.5 Hz blink rate) with the given task timings but is going too fast. This is likely due to `configCPU_CLOCK_HZ` being set incorrectly.

See #44

### PR DESCRIPTION
**Pull request by JalonWong**
I have debugged it, and it works well.
resolve  #45

### CODE REVIEW

File: freertos-rust-examples/examples/stm32-cortex-m4-blackpill/main.rs [hunk 1]
```diff
@@ -1,110 +1,106 @@
...
-// Blink 3 times long when exception occures
-    delay_n(10);
-    for _ in 0..3 {
-        // set_led(true);
-        // delay_n(1000);
-        // set_led(false);
-        // delay_n(555);
-    }
+unsafe fn HardFault(_ef: &ExceptionFrame) -> ! {
+    // Blink 3 times long when exception occures
```
Comment (schteve) [inline freertos-rust-examples/examples/stm32-cortex-m4-blackpill/main.rs:89]: Is the comment still correct? I don't see anything that would blink now.

File: .github/workflows/ci.yml [hunk 2]
```diff
@@ -93,7 +93,7 @@ jobs:
           target
         key: ${{ runner.os }}-${{ runner.arch }}
     - name: Install Rust
-      uses: dtolnay/rust-toolchain@nightly
+      uses: dtolnay/rust-toolchain@stable
```
Comment (schteve) [inline .github/workflows/ci.yml:96]: It looks like this is changing the overall build to be stable, not the examples. I'm not sure if it makes sense to switch the whole project over to stable at this time. If the goal is to build only some examples with the stable toolchain, maybe it makes sense to make a copy of the examples section that runs only the ones that work on stable?

**Review by schteve — COMMENTED** [review]
Thanks for submitting the change! Sorry it took so long to get back to you.

File: .github/workflows/ci.yml (hunk 2 above)
Comment (JalonWong) [reply .github/workflows/ci.yml:96]: First, I don't think it's necessary to keep using nightly. It's good to encourage users to use stable.
Second, the CI job didn't work. I will make them all work with the stable version.

Comment (schteve) [reply .github/workflows/ci.yml:96]: If you do end up changing each of the examples, it might be helpful to split each one into a separate PR. Easier to review and merge that way.
